### ISSUE TITLE
Copy fail error?

### ISSUE THREAD

**Issue by ToonLucas22** [ScarletStudy/DGS1-3DS-Release#33]
I've tried running the DGS1 Patcher on Luma3DS after updating both Luma3DS and boot9strap, but almost right after it starts patching it gives me this error:

> V:/autorun.gm9
line 44: copy fail
cp -w $[SOURCE]/plain.bin $[0...

I'm not sure what I did wrong?

**Comment by ltoran** [comment]
I'm in the exact same situation

**Comment by Hyarion-SS** [comment]
As nearly as we can tell, this appears to be related to an incorrectly dumped copy of DGS.

We are taking steps to mitigate this, but in the meantime, you can reinstall DGS to try to fix it.

**Comment by Hyarion-SS** [comment]
Alternatively, it would help us out if you are willing to wait a few minutes and test a patcher with a possible fix included.

**Comment by Hyarion-SS** [comment]
Here it is:
[DGS1-English-v2.3.0-PlainDotBinTest.zip](https://github.com/ScarletStudy/DGS1-3DS-Release/files/2407985/DGS1-English-v2.3.0-PlainDotBinTest.zip)

**Comment by ToonLucas22** [comment]
Well, the error stopped appearing, but now a different one appears about 5 seconds later into the patch:

> icon.icn
The file being patched does not match its checksum.

When I press A to continue, this pops up right after:

> V:/autorun.gm9
line 54: apply BPM failed
applybpm V:/DGS1-OtherData.bp...

**Comment by Hyarion-SS** [comment]
Okay, thanks. If you could sent us the contents of SD:/3DS/ScarletStudy/DGS1/Other, that would help greatly.

**Comment by ToonLucas22** [comment]
Alright then, here goes.
[DGS folder.zip](https://github.com/ScarletStudy/DGS1-3DS-Release/files/2408033/DGS.folder.zip)

**Comment by Hyarion-SS** [comment]
Please test this:
[DGS1-English-v2.3.0-PlainDotBinTest2.zip](https://github.com/ScarletStudy/DGS1-3DS-Release/files/2408065/DGS1-English-v2.3.0-PlainDotBinTest2.zip)

**Comment by ToonLucas22** [comment]
Now it patched successfully. Thanks!

**Comment by szymbar15** [comment]
I've had exactly the same issue as OP and I'm still having this issue, this time on line 59 of autorun.gm9
`apply BPM failed
applybpm: V:\DGS1-OtherData.bp...`

**Comment by Hyarion-SS** [comment]
Szy: As above, please send us the contents of SD:/3DS/ScarletStudy/DGS1/Other as a zip archive.

**Comment by szymbar15** [comment]
[Other.zip](https://github.com/ScarletStudy/DGS1-3DS-Release/files/2408077/Other.zip)
Whoops, should've been expecting this to be one of the steps of troubleshooting!
Anyway, here it is.

**Comment by barnacleman** [comment]
I had the exact same error as OP when I tried to patch. Then I tried the first fix he was given and got this:
```
ncch.bin
file being patched does not match its checksum
```
```
V:/autorun.gm9
line 54: apply BPM failed
applybpm V:/DGS1-OtherData.bp...
```
The second version of the fix gave me this:
```
icon.icn
The file being patched does not match its checksum
```
```
V:/autorun.gm9
line 61: apply BPM failed
applybpm V:/DGS1-FixBadDump.b...
```
and here is my zip file
[Other.zip](https://github.com/ScarletStudy/DGS1-3DS-Release/files/2408120/Other.zip)

**Comment by Hyarion-SS** [comment]
Szy and Barnacle: I pared the requirements back, which should hopefully put this issue to rest once and for all. Please try this.
[DGS1-English-v2.3.0-UniversalTest.zip](https://github.com/ScarletStudy/DGS1-3DS-Release/files/2408143/DGS1-English-v2.3.0-UniversalTest.zip)

**Comment by szymbar15** [comment]
I've successfully managed to create the patch, install it and run the game with "ENG 2.3.0" in the topright corner of the top screen and the save file from Episode 2 patch is still there.

Thanks a lot for coping with me/us today, the issue is solved from my side!

**Comment by Hyarion-SS** [comment]
This compatibility fix is now on the release page as v2.3.0.1. To the others in this thread, please feel free to reopen this issue if you still cannot install that version.

**Comment by Meiiye** [comment]
Hey! I'm so sorry, I'm still having this issue. When installing I get this error message: 

V:/autorun.gm9
line 22: extract .code failed 
extrcode G:/content0.game.app...

SD:/3DS/ScarletStudy/DGS1 is an empty folder.

**Comment by Meiiye** [comment]
Additional, related issue: I can't seem to get out of installing this patch to do anything else. Is there a way around this or will my DS just keep trying to install until it gets it right?
